input {
  file {
    type => "wazuh-alerts"
    path => "/var/ossec/logs/alerts/alerts.json"
    codec => "json"
    start_position => "beginning"
  }
}

filter {
  if [type] == "wazuh-alerts" {
    mutate {
      add_field => { "[@metadata][index]" => "wazuh-alerts-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  opensearch {
    hosts => ["http://opensearch:9200"]
    index => "%{[@metadata][index]}"
    ssl => false
    ssl_certificate_verification => false
  }
}
